### ISSUE TITLE
gradle 报空指针

### ISSUE THREAD

**Issue by xing16** [fuqile/AndroidBuildGradle#2]
gradle assembleRelease -PVERSION_NAME=2.1 -PAPP_ID=com.test.app 
这种方式 打包  gradle 报空指针，加了 APP_ID 就报空指针，不加就可以编译通过，请教大佬了。

**Comment by fuqile** [comment]
因为这个gradle文件里面没有定义APP_ID这个参数，可以参考VERSION_NAME的定义，具体详见我这个博客：https://blog.csdn.net/u014637428/article/details/52249423

**Comment by xing16** [comment]
我的工程里配置了 APP_ID ,我想动态修改 applicationId , 是报错的，新建的工程里又没有问题，是不是和 gradle 版本有关系？
![err](https://user-images.githubusercontent.com/11294252/50408594-f7c25b80-0826-11e9-852d-f6ce90110146.png)

**Comment by fuqile** [comment]
applicationId一般都用包名，包路径也最好对应，不建议修改，因为项目大了可能会有很多地方直接静态依赖applicationId，这时修改掉就会出现空指针。
这个跟gradle版本应该关系不大，我估计你是项目中有地方用到了applicationId，可能是写死的那种静态依赖，可以排查一下看看。

**Comment by xing16** [comment]
厉害了，是这个原因，多谢了。
